apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres
        name: postgres
        volumeMounts:
        - name: postgresdb
          mountPath: /data/db
        ports:
        - containerPort: 5432
          protocol: TCP
        envFrom:
          - secretRef:
              name: postgres-secret
      volumes:
      - name: postgresdb
        persistentVolumeClaim:
          claimName: dbclaim
