apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    protocol: TCP
#  clusterIP: None
  type: LoadBalancer
#TODO: remove IP so DB is not visible from outside the cluster
