apiVersion: v1
kind: Pod
metadata:
  name: postgres
spec:
  containers:
  - image: postgres
    name: postgres
    volumeMounts:
    - name: postgresdb
      mountPath: /data/db
    ports:
    - containerPort: 27017
      protocol: TCP
  volumes:
  - name: postgresdb
    persistentVolumeClaim:
      claimName: dbclaim
